version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.0
    - 8.2.1
  - dependency-name: linkinator
    versions:
    - 2.13.1
    - 2.13.3
    - 2.13.4
    - 2.13.5
  - dependency-name: googleapis-common
    versions:
    - 5.0.0
    - 5.0.1
  - dependency-name: typescript
    versions:
    - 3.9.8
    - 4.0.3
